project:
  type: website
  

website:
  title: "Berenice Nuno Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      light: cosmo
      dark: brand
    css: styles.css
    toc: true
